/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:17497a3c1ca91362582ecbf493098e07:3b1ec9e5c8479696e1eab38679c6f7ed:178f2f89358a5831556e3badfcaa221f$
 *
 */
namespace TextureDefinitions
{
	public class air_idle
	{
		public const string Animtion0_0 = "animtion0_0";
		public const string Animtion0_1 = "animtion0_1";
		public const string Animtion0_2 = "animtion0_2";
		public const string Animtion0_3 = "animtion0_3";
		public const string Animtion0_4 = "animtion0_4";
		public const string Animtion0_5 = "animtion0_5";
		public const string Animtion0_6 = "animtion0_6";
		public const string Animtion0_7 = "animtion0_7";
		public const string Animtion0_8 = "animtion0_8";
		public const string Animtion0_9 = "animtion0_9";
		public const string Animtion0_10 = "animtion0_10";
		public const string Animtion0_11 = "animtion0_11";
		public const string Animtion0_12 = "animtion0_12";
		public const string Animtion0_13 = "animtion0_13";
		public const string Animtion0_14 = "animtion0_14";
		public const string Animtion0_15 = "animtion0_15";
		public const string Animtion0_16 = "animtion0_16";
		public const string Animtion0_17 = "animtion0_17";
		public const string Animtion0_18 = "animtion0_18";
		public const string Animtion0_19 = "animtion0_19";
		public const string Animtion0_20 = "animtion0_20";
		public const string Animtion0_21 = "animtion0_21";
		public const string Animtion0_22 = "animtion0_22";
		public const string Animtion0_23 = "animtion0_23";

        public static string[] sprite =
            {
                Animtion0_0,
                Animtion0_1,
                Animtion0_2,
                Animtion0_3,
                Animtion0_4,
                Animtion0_5,
                Animtion0_6,
                Animtion0_7,
                Animtion0_8,
                Animtion0_9,
                Animtion0_10,
                Animtion0_11,
                Animtion0_12,
                Animtion0_13,
                Animtion0_14,
                Animtion0_15,
                Animtion0_16,
                Animtion0_17,
                Animtion0_18,
                Animtion0_19,
                Animtion0_20,
                Animtion0_21,
                Animtion0_22,
                Animtion0_23
            };
    }
}