/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:63df4d39b140c8c24e10d0d4aa1f2154:ae2ce8b5ae02aea8b283dd6b13a4761d:53de55c779c0a14fcd5c4816528f6f76$
 *
 */
namespace TextureDefinitions
{
	public class air_jump
	{
		public const string Animtion0_0 = "animtion0_0";
		public const string Animtion0_1 = "animtion0_1";
		public const string Animtion0_2 = "animtion0_2";
		public const string Animtion0_3 = "animtion0_3";
		public const string Animtion0_4 = "animtion0_4";
		public const string Animtion0_5 = "animtion0_5";
		public const string Animtion0_6 = "animtion0_6";
		public const string Animtion0_7 = "animtion0_7";
		public const string Animtion0_8 = "animtion0_8";
		public const string Animtion0_9 = "animtion0_9";
		public const string Animtion0_10 = "animtion0_10";
		public const string Animtion0_11 = "animtion0_11";
		public const string Animtion0_12 = "animtion0_12";
		public const string Animtion0_13 = "animtion0_13";
		public const string Animtion0_14 = "animtion0_14";
		public const string Animtion0_15 = "animtion0_15";
		public const string Animtion0_16 = "animtion0_16";
		public const string Animtion0_17 = "animtion0_17";

        public static string[] sprite =
            {
                Animtion0_0,
                Animtion0_1,
                Animtion0_2,
                Animtion0_3,
                Animtion0_4,
                Animtion0_5,
                Animtion0_6,
                Animtion0_7,
                Animtion0_8,
                Animtion0_9,
                Animtion0_10,
                Animtion0_11,
                Animtion0_12,
                Animtion0_13,
                Animtion0_14,
                Animtion0_15,
                Animtion0_16,
                Animtion0_17,
                Animtion0_17,
                Animtion0_17,
                Animtion0_17,
                Animtion0_17,
                Animtion0_17,
                Animtion0_17,
            };
    }
}